# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 711a64bb474d3489c6b86b73f8bdce82887c4af5ea2bc2d93bc3c40f4ae2612291c1daf6384d8a94dac98105d3a77376dae8120dbced78da45149ecdecb2f0a7

test:
  secret_key_base: 25ed0076fe624d1d1e67db3a3c839b66e4a25452510d4fa65e4072bb2fe3eb2c70dd4659138341aef05712d115bd8268bf3dc4a18be5e8e63106469009af2c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
